[package]
name = "cargo-subcommand"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Library for creating cargo subcommands."
repository = "https://github.com/dvc94ch/cargo-subcommand"
license = "ISC"

[dependencies]
cargo-project = "0.2.3"
log = "0.4.8"
